# Generated by Django 4.0.8 on 2023-01-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Организация')),
                ('faculty', models.CharField(max_length=150, verbose_name='Факультет')),
                ('specialization', models.CharField(max_length=150, verbose_name='Специализация')),
                ('start_at', models.DateField(verbose_name='Начало')),
                ('end_at', models.DateField(verbose_name='Конец')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название работы')),
                ('image', models.ImageField(upload_to='articles/')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание работы')),
                ('start_at', models.DateField(verbose_name='Начало работы')),
                ('end_at', models.DateField(verbose_name='Завершение работы')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Профессия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание работы')),
                ('start_at', models.DateField(verbose_name='Начало работы')),
                ('end_at', models.DateField(verbose_name='Окончание')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Организация')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Местонахождени')),
            ],
        ),
    ]
