# Generated by Django 4.0.8 on 2023-01-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexperience', to='users.specialist'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='users.specialist'),
        ),
        migrations.AddField(
            model_name='service',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.specialist'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='users.specialist'),
        ),
        migrations.AddField(
            model_name='education',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.specialist'),
        ),
    ]
